import type { Match, Team, Weights } from "./types";

export const eventSnapshot = {
  name: "The Injective Global Cup",
  window: "2026-07-03 to 2026-07-19",
  submission: "https://xsxo494365r.typeform.com/to/TMaGb1du",
  judgingFocus: [
    "World Cup utility",
    "clean GitHub repository",
    "clear README",
    "creative use of Injective x402, USDC CCTP, MCP Server, and Agent Skills",
  ],
};

export const defaultWeights: Weights = {
  form: 28,
  attack: 24,
  defense: 22,
  pressure: 16,
  travel: 10,
};

export const teams: Team[] = [
  {
    code: "ARG",
    name: "Argentina",
    group: "A",
    confederation: "CONMEBOL",
    fifaRank: 1,
    attack: 91,
    defense: 86,
    tempo: 78,
    setPieces: 80,
    depth: 84,
    homeTravel: 65,
    pressure: 92,
    fanMood: 88,
    note: "Best when the match becomes narrow, emotional, and decided by one late action.",
  },
  {
    code: "BRA",
    name: "Brazil",
    group: "C",
    confederation: "CONMEBOL",
    fifaRank: 5,
    attack: 94,
    defense: 83,
    tempo: 86,
    setPieces: 77,
    depth: 91,
    homeTravel: 70,
    pressure: 84,
    fanMood: 81,
    note: "Huge chance creation ceiling, with defensive spacing as the main swing factor.",
  },
  {
    code: "FRA",
    name: "France",
    group: "D",
    confederation: "UEFA",
    fifaRank: 2,
    attack: 93,
    defense: 87,
    tempo: 84,
    setPieces: 82,
    depth: 95,
    homeTravel: 59,
    pressure: 88,
    fanMood: 86,
    note: "Depth keeps the floor high across congested knockout schedules.",
  },
  {
    code: "ENG",
    name: "England",
    group: "E",
    confederation: "UEFA",
    fifaRank: 4,
    attack: 88,
    defense: 86,
    tempo: 76,
    setPieces: 88,
    depth: 90,
    homeTravel: 58,
    pressure: 80,
    fanMood: 76,
    note: "Set pieces and control are reliable; chance speed drops when trailing.",
  },
  {
    code: "ESP",
    name: "Spain",
    group: "B",
    confederation: "UEFA",
    fifaRank: 6,
    attack: 86,
    defense: 88,
    tempo: 90,
    setPieces: 74,
    depth: 87,
    homeTravel: 56,
    pressure: 83,
    fanMood: 84,
    note: "Controls field tilt and territory, but needs early final-third efficiency.",
  },
  {
    code: "GER",
    name: "Germany",
    group: "F",
    confederation: "UEFA",
    fifaRank: 10,
    attack: 86,
    defense: 80,
    tempo: 82,
    setPieces: 83,
    depth: 84,
    homeTravel: 57,
    pressure: 79,
    fanMood: 78,
    note: "Better when the game is open; risk appears in defensive rest positions.",
  },
  {
    code: "POR",
    name: "Portugal",
    group: "G",
    confederation: "UEFA",
    fifaRank: 7,
    attack: 89,
    defense: 82,
    tempo: 83,
    setPieces: 79,
    depth: 89,
    homeTravel: 58,
    pressure: 82,
    fanMood: 80,
    note: "A flexible creator pool makes bench timing very important.",
  },
  {
    code: "NED",
    name: "Netherlands",
    group: "H",
    confederation: "UEFA",
    fifaRank: 8,
    attack: 84,
    defense: 87,
    tempo: 80,
    setPieces: 85,
    depth: 82,
    homeTravel: 57,
    pressure: 81,
    fanMood: 79,
    note: "Back line security and aerial threat create a strong knockout profile.",
  },
  {
    code: "USA",
    name: "United States",
    group: "I",
    confederation: "CONCACAF",
    fifaRank: 11,
    attack: 82,
    defense: 78,
    tempo: 88,
    setPieces: 76,
    depth: 80,
    homeTravel: 97,
    pressure: 75,
    fanMood: 91,
    note: "Host energy and transition speed can tilt live momentum quickly.",
  },
  {
    code: "MEX",
    name: "Mexico",
    group: "A",
    confederation: "CONCACAF",
    fifaRank: 15,
    attack: 80,
    defense: 78,
    tempo: 82,
    setPieces: 79,
    depth: 77,
    homeTravel: 96,
    pressure: 77,
    fanMood: 93,
    note: "Home-field rhythm matters; the first 20 minutes often define match texture.",
  },
  {
    code: "JPN",
    name: "Japan",
    group: "J",
    confederation: "AFC",
    fifaRank: 17,
    attack: 81,
    defense: 80,
    tempo: 89,
    setPieces: 73,
    depth: 79,
    homeTravel: 51,
    pressure: 78,
    fanMood: 82,
    note: "High timing quality and counters make underdog games uncomfortable.",
  },
  {
    code: "MAR",
    name: "Morocco",
    group: "C",
    confederation: "CAF",
    fifaRank: 12,
    attack: 79,
    defense: 86,
    tempo: 78,
    setPieces: 80,
    depth: 78,
    homeTravel: 60,
    pressure: 85,
    fanMood: 87,
    note: "Compact shape and emotional control make them a hard knockout opponent.",
  },
];

export const matches: Match[] = [
  {
    id: "cup-001",
    round: "Group A",
    venue: "Estadio Azteca, Mexico City",
    kickoffLocal: "2026-07-04 20:00 CST",
    home: "MEX",
    away: "ARG",
    status: "live",
    minute: 64,
    homeGoals: 1,
    awayGoals: 1,
    xgHome: 1.26,
    xgAway: 1.54,
    shotPressureHome: 57,
    shotPressureAway: 63,
    weather: "dry",
    liveDataSource: "Demo feed seeded from public-style match events; replace with provider API before production.",
  },
  {
    id: "cup-002",
    round: "Group C",
    venue: "Hard Rock Stadium, Miami",
    kickoffLocal: "2026-07-05 18:00 EDT",
    home: "BRA",
    away: "MAR",
    status: "upcoming",
    xgHome: 1.88,
    xgAway: 1.09,
    shotPressureHome: 68,
    shotPressureAway: 51,
    weather: "humid",
    liveDataSource: "Fixture scout model plus humidity adjustment.",
  },
  {
    id: "cup-003",
    round: "Group D",
    venue: "MetLife Stadium, New Jersey",
    kickoffLocal: "2026-07-06 21:00 EDT",
    home: "USA",
    away: "FRA",
    status: "upcoming",
    xgHome: 1.18,
    xgAway: 1.74,
    shotPressureHome: 59,
    shotPressureAway: 69,
    weather: "rain",
    liveDataSource: "Fixture scout model plus host-travel adjustment.",
  },
  {
    id: "cup-004",
    round: "Group E",
    venue: "BC Place, Vancouver",
    kickoffLocal: "2026-07-07 17:00 PDT",
    home: "ENG",
    away: "JPN",
    status: "upcoming",
    xgHome: 1.52,
    xgAway: 1.22,
    shotPressureHome: 61,
    shotPressureAway: 58,
    weather: "indoor",
    liveDataSource: "Fixture scout model with indoor tempo lift.",
  },
];

export function teamByCode(code: Team["code"]): Team {
  const team = teams.find((candidate) => candidate.code === code);
  if (!team) throw new Error(`Unknown team code: ${code}`);
  return team;
}
