// Generated from reference repositories:
// - openfootball/worldcup for Football.TXT context and knockout schedule slots
// - rezarahiminia/worldcup2026 CSV data for 48 teams, 12 groups, group matches, and 16 stadiums

export type WorldCupTeam = { id: number; name: string; fifaCode: string; iso2: string; group: string; flag: string };
export type WorldCupStadium = { id: number; name: string; city: string; country: string; capacity: number };
export type WorldCupMatch = { id: number; type: string; group: string; matchday: number; localDate: string; date: string; home: string; away: string; homeName: string; awayName: string; stadium: string; city: string; country: string; source: string };
export type WorldCupGroup = { group: string; teams: string[] };

export const worldCupSource = {
  teams: "rezarahiminia/worldcup2026/worldcup2026.teams.csv",
  groupMatches: "rezarahiminia/worldcup2026/worldcup2026.games.csv",
  stadiums: "rezarahiminia/worldcup2026/worldcup2026.stadia.csv",
  knockout: "openfootball/worldcup/2026--usa/cup_finals.txt",
  context: "openfootball/worldcup/2026--usa/cup.txt",
};

export const worldCupTeams: WorldCupTeam[] = [
  {
    "id": 1,
    "name": "Mexico",
    "fifaCode": "MEX",
    "iso2": "MX",
    "group": "A",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png"
  },
  {
    "id": 2,
    "name": "South Africa",
    "fifaCode": "RSA",
    "iso2": "ZA",
    "group": "A",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/125px-Flag_of_South_Africa.svg.png"
  },
  {
    "id": 3,
    "name": "South Korea",
    "fifaCode": "KOR",
    "iso2": "KR",
    "group": "A",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png"
  },
  {
    "id": 4,
    "name": "UEFA Path D Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "A",
    "flag": ""
  },
  {
    "id": 5,
    "name": "Canada",
    "fifaCode": "CAN",
    "iso2": "CA",
    "group": "B",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png"
  },
  {
    "id": 6,
    "name": "UEFA Path A Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "B",
    "flag": ""
  },
  {
    "id": 7,
    "name": "Qatar",
    "fifaCode": "QAT",
    "iso2": "QA",
    "group": "B",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png"
  },
  {
    "id": 8,
    "name": "Switzerland",
    "fifaCode": "SUI",
    "iso2": "CH",
    "group": "B",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png"
  },
  {
    "id": 9,
    "name": "Brazil",
    "fifaCode": "BRA",
    "iso2": "BR",
    "group": "C",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png"
  },
  {
    "id": 10,
    "name": "Morocco",
    "fifaCode": "MAR",
    "iso2": "MA",
    "group": "C",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png"
  },
  {
    "id": 11,
    "name": "Haiti",
    "fifaCode": "HAI",
    "iso2": "HT",
    "group": "C",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/125px-Flag_of_Haiti.svg.png"
  },
  {
    "id": 12,
    "name": "Scotland",
    "fifaCode": "SCO",
    "iso2": "SCO",
    "group": "C",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Flag_of_Scotland.svg/125px-Flag_of_Scotland.svg.png"
  },
  {
    "id": 13,
    "name": "United States",
    "fifaCode": "USA",
    "iso2": "US",
    "group": "D",
    "flag": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png"
  },
  {
    "id": 14,
    "name": "Paraguay",
    "fifaCode": "PAR",
    "iso2": "PY",
    "group": "D",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/125px-Flag_of_Paraguay.svg.png"
  },
  {
    "id": 15,
    "name": "Australia",
    "fifaCode": "AUS",
    "iso2": "AU",
    "group": "D",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png"
  },
  {
    "id": 16,
    "name": "UEFA Path C Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "D",
    "flag": ""
  },
  {
    "id": 17,
    "name": "Germany",
    "fifaCode": "GER",
    "iso2": "DE",
    "group": "E",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png"
  },
  {
    "id": 18,
    "name": "Curaçao",
    "fifaCode": "CUW",
    "iso2": "CW",
    "group": "E",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/125px-Flag_of_Cura%C3%A7ao.svg.png"
  },
  {
    "id": 19,
    "name": "Ivory Coast",
    "fifaCode": "CIV",
    "iso2": "CI",
    "group": "E",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/125px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png"
  },
  {
    "id": 20,
    "name": "Ecuador",
    "fifaCode": "ECU",
    "iso2": "EC",
    "group": "E",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png"
  },
  {
    "id": 21,
    "name": "Netherlands",
    "fifaCode": "NED",
    "iso2": "NL",
    "group": "F",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png"
  },
  {
    "id": 22,
    "name": "Japan",
    "fifaCode": "JPN",
    "iso2": "JP",
    "group": "F",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png"
  },
  {
    "id": 23,
    "name": "UEFA Path B Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "F",
    "flag": ""
  },
  {
    "id": 24,
    "name": "Tunisia",
    "fifaCode": "TUN",
    "iso2": "TN",
    "group": "F",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png"
  },
  {
    "id": 25,
    "name": "Belgium",
    "fifaCode": "BEL",
    "iso2": "BE",
    "group": "G",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png"
  },
  {
    "id": 26,
    "name": "Egypt",
    "fifaCode": "EGY",
    "iso2": "EG",
    "group": "G",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/125px-Flag_of_Egypt.svg.png"
  },
  {
    "id": 27,
    "name": "Iran",
    "fifaCode": "IRN",
    "iso2": "IR",
    "group": "G",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
  },
  {
    "id": 28,
    "name": "New Zealand",
    "fifaCode": "NZL",
    "iso2": "NZ",
    "group": "G",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/125px-Flag_of_New_Zealand.svg.png"
  },
  {
    "id": 29,
    "name": "Spain",
    "fifaCode": "ESP",
    "iso2": "ES",
    "group": "H",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png"
  },
  {
    "id": 30,
    "name": "Cape Verde",
    "fifaCode": "CPV",
    "iso2": "CV",
    "group": "H",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/125px-Flag_of_Cape_Verde.svg.png"
  },
  {
    "id": 31,
    "name": "Saudi Arabia",
    "fifaCode": "KSA",
    "iso2": "SA",
    "group": "H",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png"
  },
  {
    "id": 32,
    "name": "Uruguay",
    "fifaCode": "URU",
    "iso2": "UY",
    "group": "H",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png"
  },
  {
    "id": 33,
    "name": "France",
    "fifaCode": "FRA",
    "iso2": "FR",
    "group": "I",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/125px-Flag_of_France.svg.png"
  },
  {
    "id": 34,
    "name": "Senegal",
    "fifaCode": "SEN",
    "iso2": "SN",
    "group": "I",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png"
  },
  {
    "id": 35,
    "name": "IC Path 2 Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "I",
    "flag": ""
  },
  {
    "id": 36,
    "name": "Norway",
    "fifaCode": "NOR",
    "iso2": "NO",
    "group": "I",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/125px-Flag_of_Norway.svg.png"
  },
  {
    "id": 37,
    "name": "Argentina",
    "fifaCode": "ARG",
    "iso2": "AR",
    "group": "J",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png"
  },
  {
    "id": 38,
    "name": "Algeria",
    "fifaCode": "ALG",
    "iso2": "DZ",
    "group": "J",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/125px-Flag_of_Algeria.svg.png"
  },
  {
    "id": 39,
    "name": "Austria",
    "fifaCode": "AUT",
    "iso2": "AT",
    "group": "J",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/125px-Flag_of_Austria.svg.png"
  },
  {
    "id": 40,
    "name": "Jordan",
    "fifaCode": "JOR",
    "iso2": "JO",
    "group": "J",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/125px-Flag_of_Jordan.svg.png"
  },
  {
    "id": 41,
    "name": "Portugal",
    "fifaCode": "POR",
    "iso2": "PT",
    "group": "K",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png"
  },
  {
    "id": 42,
    "name": "IC Path 1 Winner",
    "fifaCode": "TBD",
    "iso2": "TBD",
    "group": "K",
    "flag": ""
  },
  {
    "id": 43,
    "name": "Uzbekistan",
    "fifaCode": "UZB",
    "iso2": "UZ",
    "group": "K",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/125px-Flag_of_Uzbekistan.svg.png"
  },
  {
    "id": 44,
    "name": "Colombia",
    "fifaCode": "COL",
    "iso2": "CO",
    "group": "K",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/125px-Flag_of_Colombia.svg.png"
  },
  {
    "id": 45,
    "name": "England",
    "fifaCode": "ENG",
    "iso2": "ENG",
    "group": "L",
    "flag": "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png"
  },
  {
    "id": 46,
    "name": "Croatia",
    "fifaCode": "CRO",
    "iso2": "HR",
    "group": "L",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png"
  },
  {
    "id": 47,
    "name": "Ghana",
    "fifaCode": "GHA",
    "iso2": "GH",
    "group": "L",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png"
  },
  {
    "id": 48,
    "name": "Panama",
    "fifaCode": "PAN",
    "iso2": "PA",
    "group": "L",
    "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/125px-Flag_of_Panama.svg.png"
  }
];

export const worldCupStadiums: WorldCupStadium[] = [
  {
    "id": 1,
    "name": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "capacity": 83000
  },
  {
    "id": 2,
    "name": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "capacity": 48000
  },
  {
    "id": 3,
    "name": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "capacity": 53500
  },
  {
    "id": 4,
    "name": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "capacity": 94000
  },
  {
    "id": 5,
    "name": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "capacity": 72000
  },
  {
    "id": 6,
    "name": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "capacity": 73000
  },
  {
    "id": 7,
    "name": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "capacity": 75000
  },
  {
    "id": 8,
    "name": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "capacity": 65000
  },
  {
    "id": 9,
    "name": "Gillette Stadium",
    "city": "Boston (Foxborough)",
    "country": "United States",
    "capacity": 65000
  },
  {
    "id": 10,
    "name": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "capacity": 69000
  },
  {
    "id": 11,
    "name": "MetLife Stadium",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "United States",
    "capacity": 82500
  },
  {
    "id": 12,
    "name": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "capacity": 45000
  },
  {
    "id": 13,
    "name": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "capacity": 54000
  },
  {
    "id": 14,
    "name": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "capacity": 69000
  },
  {
    "id": 15,
    "name": "Levi's Stadium",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "United States",
    "capacity": 71000
  },
  {
    "id": 16,
    "name": "SoFi Stadium",
    "city": "Los Angeles (Inglewood)",
    "country": "United States",
    "capacity": 70000
  }
];

export const worldCupGroups: WorldCupGroup[] = [
  {
    "group": "A",
    "teams": [
      "MEX",
      "RSA",
      "KOR",
      "TBD"
    ]
  },
  {
    "group": "B",
    "teams": [
      "CAN",
      "TBD",
      "QAT",
      "SUI"
    ]
  },
  {
    "group": "C",
    "teams": [
      "BRA",
      "MAR",
      "HAI",
      "SCO"
    ]
  },
  {
    "group": "D",
    "teams": [
      "USA",
      "PAR",
      "AUS",
      "TBD"
    ]
  },
  {
    "group": "E",
    "teams": [
      "GER",
      "CUW",
      "CIV",
      "ECU"
    ]
  },
  {
    "group": "F",
    "teams": [
      "NED",
      "JPN",
      "TBD",
      "TUN"
    ]
  },
  {
    "group": "G",
    "teams": [
      "BEL",
      "EGY",
      "IRN",
      "NZL"
    ]
  },
  {
    "group": "H",
    "teams": [
      "ESP",
      "CPV",
      "KSA",
      "URU"
    ]
  },
  {
    "group": "I",
    "teams": [
      "FRA",
      "SEN",
      "TBD",
      "NOR"
    ]
  },
  {
    "group": "J",
    "teams": [
      "ARG",
      "ALG",
      "AUT",
      "JOR"
    ]
  },
  {
    "group": "K",
    "teams": [
      "POR",
      "TBD",
      "UZB",
      "COL"
    ]
  },
  {
    "group": "L",
    "teams": [
      "ENG",
      "CRO",
      "GHA",
      "PAN"
    ]
  }
];

export const worldCupMatches: WorldCupMatch[] = [
  {
    "id": 1,
    "type": "group",
    "group": "A",
    "matchday": 1,
    "localDate": "06/11/2026 13:00",
    "date": "2026-06-11T09:30:00.000Z",
    "home": "MEX",
    "away": "RSA",
    "homeName": "Mexico",
    "awayName": "South Africa",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 2,
    "type": "group",
    "group": "A",
    "matchday": 1,
    "localDate": "06/11/2026 20:00",
    "date": "2026-06-11T16:30:00.000Z",
    "home": "KOR",
    "away": "TBD",
    "homeName": "South Korea",
    "awayName": "UEFA Path D Winner",
    "stadium": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 3,
    "type": "group",
    "group": "B",
    "matchday": 1,
    "localDate": "06/12/2026 15:00",
    "date": "2026-06-12T11:30:00.000Z",
    "home": "CAN",
    "away": "TBD",
    "homeName": "Canada",
    "awayName": "UEFA Path A Winner",
    "stadium": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 4,
    "type": "group",
    "group": "D",
    "matchday": 1,
    "localDate": "06/12/2026 18:00",
    "date": "2026-06-12T14:30:00.000Z",
    "home": "USA",
    "away": "PAR",
    "homeName": "United States",
    "awayName": "Paraguay",
    "stadium": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 5,
    "type": "group",
    "group": "C",
    "matchday": 1,
    "localDate": "06/13/2026 21:00",
    "date": "2026-06-13T17:30:00.000Z",
    "home": "HAI",
    "away": "SCO",
    "homeName": "Haiti",
    "awayName": "Scotland",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 6,
    "type": "group",
    "group": "D",
    "matchday": 1,
    "localDate": "06/13/2026 12:00",
    "date": "2026-06-13T08:30:00.000Z",
    "home": "AUS",
    "away": "TBD",
    "homeName": "Australia",
    "awayName": "UEFA Path C Winner",
    "stadium": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 7,
    "type": "group",
    "group": "C",
    "matchday": 1,
    "localDate": "06/13/2026 18:00",
    "date": "2026-06-13T14:30:00.000Z",
    "home": "BRA",
    "away": "MAR",
    "homeName": "Brazil",
    "awayName": "Morocco",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 8,
    "type": "group",
    "group": "B",
    "matchday": 1,
    "localDate": "06/13/2026 12:00",
    "date": "2026-06-13T08:30:00.000Z",
    "home": "QAT",
    "away": "SUI",
    "homeName": "Qatar",
    "awayName": "Switzerland",
    "stadium": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 9,
    "type": "group",
    "group": "E",
    "matchday": 1,
    "localDate": "06/14/2026 18:00",
    "date": "2026-06-14T14:30:00.000Z",
    "home": "CIV",
    "away": "ECU",
    "homeName": "Ivory Coast",
    "awayName": "Ecuador",
    "stadium": "Gillette Stadium",
    "city": "Boston (Foxborough)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 10,
    "type": "group",
    "group": "E",
    "matchday": 1,
    "localDate": "06/14/2026 12:00",
    "date": "2026-06-14T08:30:00.000Z",
    "home": "GER",
    "away": "CUW",
    "homeName": "Germany",
    "awayName": "Curaçao",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 11,
    "type": "group",
    "group": "F",
    "matchday": 1,
    "localDate": "06/14/2026 15:00",
    "date": "2026-06-14T11:30:00.000Z",
    "home": "NED",
    "away": "JPN",
    "homeName": "Netherlands",
    "awayName": "Japan",
    "stadium": "MetLife Stadium",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 12,
    "type": "group",
    "group": "F",
    "matchday": 1,
    "localDate": "06/14/2026 21:00",
    "date": "2026-06-14T17:30:00.000Z",
    "home": "TBD",
    "away": "TUN",
    "homeName": "UEFA Path B Winner",
    "awayName": "Tunisia",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 13,
    "type": "group",
    "group": "G",
    "matchday": 1,
    "localDate": "06/15/2026 18:00",
    "date": "2026-06-15T14:30:00.000Z",
    "home": "IRN",
    "away": "NZL",
    "homeName": "Iran",
    "awayName": "New Zealand",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 14,
    "type": "group",
    "group": "H",
    "matchday": 1,
    "localDate": "06/15/2026 12:00",
    "date": "2026-06-15T08:30:00.000Z",
    "home": "ESP",
    "away": "CPV",
    "homeName": "Spain",
    "awayName": "Cape Verde",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 15,
    "type": "group",
    "group": "G",
    "matchday": 1,
    "localDate": "06/15/2026 15:00",
    "date": "2026-06-15T11:30:00.000Z",
    "home": "BEL",
    "away": "EGY",
    "homeName": "Belgium",
    "awayName": "Egypt",
    "stadium": "Levi's Stadium",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 16,
    "type": "group",
    "group": "H",
    "matchday": 1,
    "localDate": "06/15/2026 21:00",
    "date": "2026-06-15T17:30:00.000Z",
    "home": "KSA",
    "away": "URU",
    "homeName": "Saudi Arabia",
    "awayName": "Uruguay",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles (Inglewood)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 17,
    "type": "group",
    "group": "I",
    "matchday": 1,
    "localDate": "06/16/2026 15:00",
    "date": "2026-06-16T11:30:00.000Z",
    "home": "FRA",
    "away": "SEN",
    "homeName": "France",
    "awayName": "Senegal",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 18,
    "type": "group",
    "group": "I",
    "matchday": 1,
    "localDate": "06/16/2026 18:00",
    "date": "2026-06-16T14:30:00.000Z",
    "home": "TBD",
    "away": "NOR",
    "homeName": "IC Path 2 Winner",
    "awayName": "Norway",
    "stadium": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 19,
    "type": "group",
    "group": "J",
    "matchday": 1,
    "localDate": "06/16/2026 20:00",
    "date": "2026-06-16T16:30:00.000Z",
    "home": "ARG",
    "away": "ALG",
    "homeName": "Argentina",
    "awayName": "Algeria",
    "stadium": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 20,
    "type": "group",
    "group": "J",
    "matchday": 1,
    "localDate": "06/16/2026 12:00",
    "date": "2026-06-16T08:30:00.000Z",
    "home": "AUT",
    "away": "JOR",
    "homeName": "Austria",
    "awayName": "Jordan",
    "stadium": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 21,
    "type": "group",
    "group": "K",
    "matchday": 1,
    "localDate": "06/17/2026 12:00",
    "date": "2026-06-17T08:30:00.000Z",
    "home": "POR",
    "away": "TBD",
    "homeName": "Portugal",
    "awayName": "IC Path 1 Winner",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 22,
    "type": "group",
    "group": "L",
    "matchday": 1,
    "localDate": "06/17/2026 15:00",
    "date": "2026-06-17T11:30:00.000Z",
    "home": "ENG",
    "away": "CRO",
    "homeName": "England",
    "awayName": "Croatia",
    "stadium": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 23,
    "type": "group",
    "group": "K",
    "matchday": 1,
    "localDate": "06/17/2026 18:00",
    "date": "2026-06-17T14:30:00.000Z",
    "home": "UZB",
    "away": "COL",
    "homeName": "Uzbekistan",
    "awayName": "Colombia",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 24,
    "type": "group",
    "group": "L",
    "matchday": 1,
    "localDate": "06/17/2026 21:00",
    "date": "2026-06-17T17:30:00.000Z",
    "home": "GHA",
    "away": "PAN",
    "homeName": "Ghana",
    "awayName": "Panama",
    "stadium": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 25,
    "type": "group",
    "group": "A",
    "matchday": 2,
    "localDate": "06/18/2026 13:00",
    "date": "2026-06-18T09:30:00.000Z",
    "home": "MEX",
    "away": "KOR",
    "homeName": "Mexico",
    "awayName": "South Korea",
    "stadium": "Gillette Stadium",
    "city": "Boston (Foxborough)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 26,
    "type": "group",
    "group": "B",
    "matchday": 2,
    "localDate": "06/18/2026 12:00",
    "date": "2026-06-18T08:30:00.000Z",
    "home": "SUI",
    "away": "TBD",
    "homeName": "Switzerland",
    "awayName": "UEFA Path A Winner",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 27,
    "type": "group",
    "group": "B",
    "matchday": 2,
    "localDate": "06/18/2026 15:00",
    "date": "2026-06-18T11:30:00.000Z",
    "home": "CAN",
    "away": "QAT",
    "homeName": "Canada",
    "awayName": "Qatar",
    "stadium": "MetLife Stadium",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 28,
    "type": "group",
    "group": "A",
    "matchday": 2,
    "localDate": "06/18/2026 18:00",
    "date": "2026-06-18T14:30:00.000Z",
    "home": "TBD",
    "away": "RSA",
    "homeName": "UEFA Path D Winner",
    "awayName": "South Africa",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 29,
    "type": "group",
    "group": "C",
    "matchday": 2,
    "localDate": "06/19/2026 21:00",
    "date": "2026-06-19T17:30:00.000Z",
    "home": "BRA",
    "away": "HAI",
    "homeName": "Brazil",
    "awayName": "Haiti",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 30,
    "type": "group",
    "group": "C",
    "matchday": 2,
    "localDate": "06/19/2026 18:00",
    "date": "2026-06-19T14:30:00.000Z",
    "home": "SCO",
    "away": "MAR",
    "homeName": "Scotland",
    "awayName": "Morocco",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 31,
    "type": "group",
    "group": "D",
    "matchday": 2,
    "localDate": "06/19/2026 12:00",
    "date": "2026-06-19T08:30:00.000Z",
    "home": "USA",
    "away": "AUS",
    "homeName": "United States",
    "awayName": "Australia",
    "stadium": "Levi's Stadium",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 32,
    "type": "group",
    "group": "D",
    "matchday": 2,
    "localDate": "06/19/2026 15:00",
    "date": "2026-06-19T11:30:00.000Z",
    "home": "TBD",
    "away": "PAR",
    "homeName": "UEFA Path C Winner",
    "awayName": "Paraguay",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles (Inglewood)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 33,
    "type": "group",
    "group": "E",
    "matchday": 2,
    "localDate": "06/20/2026 19:00",
    "date": "2026-06-20T15:30:00.000Z",
    "home": "GER",
    "away": "CIV",
    "homeName": "Germany",
    "awayName": "Ivory Coast",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 34,
    "type": "group",
    "group": "E",
    "matchday": 2,
    "localDate": "06/20/2026 19:00",
    "date": "2026-06-20T15:30:00.000Z",
    "home": "ECU",
    "away": "CUW",
    "homeName": "Ecuador",
    "awayName": "Curaçao",
    "stadium": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 35,
    "type": "group",
    "group": "F",
    "matchday": 2,
    "localDate": "06/20/2026 12:00",
    "date": "2026-06-20T08:30:00.000Z",
    "home": "NED",
    "away": "TBD",
    "homeName": "Netherlands",
    "awayName": "UEFA Path B Winner",
    "stadium": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 36,
    "type": "group",
    "group": "F",
    "matchday": 2,
    "localDate": "06/20/2026 15:00",
    "date": "2026-06-20T11:30:00.000Z",
    "home": "TUN",
    "away": "JPN",
    "homeName": "Tunisia",
    "awayName": "Japan",
    "stadium": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 37,
    "type": "group",
    "group": "G",
    "matchday": 2,
    "localDate": "06/21/2026 15:00",
    "date": "2026-06-21T11:30:00.000Z",
    "home": "BEL",
    "away": "IRN",
    "homeName": "Belgium",
    "awayName": "Iran",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 38,
    "type": "group",
    "group": "G",
    "matchday": 2,
    "localDate": "06/21/2026 12:00",
    "date": "2026-06-21T08:30:00.000Z",
    "home": "NZL",
    "away": "EGY",
    "homeName": "New Zealand",
    "awayName": "Egypt",
    "stadium": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 39,
    "type": "group",
    "group": "H",
    "matchday": 2,
    "localDate": "06/21/2026 18:00",
    "date": "2026-06-21T14:30:00.000Z",
    "home": "ESP",
    "away": "KSA",
    "homeName": "Spain",
    "awayName": "Saudi Arabia",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 40,
    "type": "group",
    "group": "H",
    "matchday": 2,
    "localDate": "06/21/2026 21:00",
    "date": "2026-06-21T17:30:00.000Z",
    "home": "URU",
    "away": "CPV",
    "homeName": "Uruguay",
    "awayName": "Cape Verde",
    "stadium": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 41,
    "type": "group",
    "group": "I",
    "matchday": 2,
    "localDate": "06/22/2026 17:00",
    "date": "2026-06-22T13:30:00.000Z",
    "home": "FRA",
    "away": "TBD",
    "homeName": "France",
    "awayName": "IC Path 2 Winner",
    "stadium": "Gillette Stadium",
    "city": "Boston (Foxborough)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 42,
    "type": "group",
    "group": "I",
    "matchday": 2,
    "localDate": "06/22/2026 14:00",
    "date": "2026-06-22T10:30:00.000Z",
    "home": "NOR",
    "away": "SEN",
    "homeName": "Norway",
    "awayName": "Senegal",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 43,
    "type": "group",
    "group": "J",
    "matchday": 2,
    "localDate": "06/22/2026 20:00",
    "date": "2026-06-22T16:30:00.000Z",
    "home": "ARG",
    "away": "AUT",
    "homeName": "Argentina",
    "awayName": "Austria",
    "stadium": "MetLife Stadium",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 44,
    "type": "group",
    "group": "J",
    "matchday": 2,
    "localDate": "06/22/2026 11:00",
    "date": "2026-06-22T07:30:00.000Z",
    "home": "JOR",
    "away": "ALG",
    "homeName": "Jordan",
    "awayName": "Algeria",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 45,
    "type": "group",
    "group": "K",
    "matchday": 2,
    "localDate": "06/23/2026 15:00",
    "date": "2026-06-23T11:30:00.000Z",
    "home": "POR",
    "away": "UZB",
    "homeName": "Portugal",
    "awayName": "Uzbekistan",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 46,
    "type": "group",
    "group": "L",
    "matchday": 2,
    "localDate": "06/23/2026 19:00",
    "date": "2026-06-23T15:30:00.000Z",
    "home": "PAN",
    "away": "CRO",
    "homeName": "Panama",
    "awayName": "Croatia",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 47,
    "type": "group",
    "group": "K",
    "matchday": 2,
    "localDate": "06/23/2026 12:00",
    "date": "2026-06-23T08:30:00.000Z",
    "home": "COL",
    "away": "TBD",
    "homeName": "Colombia",
    "awayName": "IC Path 1 Winner",
    "stadium": "Levi's Stadium",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 48,
    "type": "group",
    "group": "L",
    "matchday": 2,
    "localDate": "06/23/2026 21:00",
    "date": "2026-06-23T17:30:00.000Z",
    "home": "ENG",
    "away": "GHA",
    "homeName": "England",
    "awayName": "Ghana",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles (Inglewood)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 49,
    "type": "group",
    "group": "C",
    "matchday": 3,
    "localDate": "06/24/2026 18:00",
    "date": "2026-06-24T14:30:00.000Z",
    "home": "SCO",
    "away": "BRA",
    "homeName": "Scotland",
    "awayName": "Brazil",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 50,
    "type": "group",
    "group": "C",
    "matchday": 3,
    "localDate": "06/24/2026 18:00",
    "date": "2026-06-24T14:30:00.000Z",
    "home": "MAR",
    "away": "HAI",
    "homeName": "Morocco",
    "awayName": "Haiti",
    "stadium": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 51,
    "type": "group",
    "group": "A",
    "matchday": 3,
    "localDate": "06/24/2026 19:00",
    "date": "2026-06-24T15:30:00.000Z",
    "home": "RSA",
    "away": "KOR",
    "homeName": "South Africa",
    "awayName": "South Korea",
    "stadium": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 52,
    "type": "group",
    "group": "A",
    "matchday": 3,
    "localDate": "06/24/2026 19:00",
    "date": "2026-06-24T15:30:00.000Z",
    "home": "TBD",
    "away": "MEX",
    "homeName": "UEFA Path D Winner",
    "awayName": "Mexico",
    "stadium": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 53,
    "type": "group",
    "group": "B",
    "matchday": 3,
    "localDate": "06/25/2026 18:00",
    "date": "2026-06-25T14:30:00.000Z",
    "home": "TBD",
    "away": "CAN",
    "homeName": "UEFA Path A Winner",
    "awayName": "Canada",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 54,
    "type": "group",
    "group": "B",
    "matchday": 3,
    "localDate": "06/25/2026 18:00",
    "date": "2026-06-25T14:30:00.000Z",
    "home": "QAT",
    "away": "SUI",
    "homeName": "Qatar",
    "awayName": "Switzerland",
    "stadium": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 55,
    "type": "group",
    "group": "E",
    "matchday": 3,
    "localDate": "06/25/2026 16:00",
    "date": "2026-06-25T12:30:00.000Z",
    "home": "CUW",
    "away": "CIV",
    "homeName": "Curaçao",
    "awayName": "Ivory Coast",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 56,
    "type": "group",
    "group": "E",
    "matchday": 3,
    "localDate": "06/25/2026 16:00",
    "date": "2026-06-25T12:30:00.000Z",
    "home": "ECU",
    "away": "GER",
    "homeName": "Ecuador",
    "awayName": "Germany",
    "stadium": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 57,
    "type": "group",
    "group": "D",
    "matchday": 3,
    "localDate": "06/25/2026 19:00",
    "date": "2026-06-25T15:30:00.000Z",
    "home": "PAR",
    "away": "AUS",
    "homeName": "Paraguay",
    "awayName": "Australia",
    "stadium": "Gillette Stadium",
    "city": "Boston (Foxborough)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 58,
    "type": "group",
    "group": "D",
    "matchday": 3,
    "localDate": "06/25/2026 19:00",
    "date": "2026-06-25T15:30:00.000Z",
    "home": "TBD",
    "away": "USA",
    "homeName": "UEFA Path C Winner",
    "awayName": "United States",
    "stadium": "Lincoln Financial Field",
    "city": "Philadelphia",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 59,
    "type": "group",
    "group": "F",
    "matchday": 3,
    "localDate": "06/26/2026 18:00",
    "date": "2026-06-26T14:30:00.000Z",
    "home": "JPN",
    "away": "TBD",
    "homeName": "Japan",
    "awayName": "UEFA Path B Winner",
    "stadium": "MetLife Stadium",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 60,
    "type": "group",
    "group": "F",
    "matchday": 3,
    "localDate": "06/26/2026 18:00",
    "date": "2026-06-26T14:30:00.000Z",
    "home": "TUN",
    "away": "NED",
    "homeName": "Tunisia",
    "awayName": "Netherlands",
    "stadium": "BMO Field",
    "city": "Toronto",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 61,
    "type": "group",
    "group": "I",
    "matchday": 3,
    "localDate": "06/26/2026 15:00",
    "date": "2026-06-26T11:30:00.000Z",
    "home": "SEN",
    "away": "TBD",
    "homeName": "Senegal",
    "awayName": "IC Path 2 Winner",
    "stadium": "BC Place",
    "city": "Vancouver",
    "country": "Canada",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 62,
    "type": "group",
    "group": "I",
    "matchday": 3,
    "localDate": "06/26/2026 15:00",
    "date": "2026-06-26T11:30:00.000Z",
    "home": "NOR",
    "away": "FRA",
    "homeName": "Norway",
    "awayName": "France",
    "stadium": "Lumen Field",
    "city": "Seattle",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 63,
    "type": "group",
    "group": "G",
    "matchday": 3,
    "localDate": "06/26/2026 20:00",
    "date": "2026-06-26T16:30:00.000Z",
    "home": "EGY",
    "away": "IRN",
    "homeName": "Egypt",
    "awayName": "Iran",
    "stadium": "Levi's Stadium",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 64,
    "type": "group",
    "group": "G",
    "matchday": 3,
    "localDate": "06/26/2026 20:00",
    "date": "2026-06-26T16:30:00.000Z",
    "home": "NZL",
    "away": "BEL",
    "homeName": "New Zealand",
    "awayName": "Belgium",
    "stadium": "SoFi Stadium",
    "city": "Los Angeles (Inglewood)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 65,
    "type": "group",
    "group": "H",
    "matchday": 3,
    "localDate": "06/27/2026 17:00",
    "date": "2026-06-27T13:30:00.000Z",
    "home": "CPV",
    "away": "KSA",
    "homeName": "Cape Verde",
    "awayName": "Saudi Arabia",
    "stadium": "Estadio Azteca",
    "city": "Mexico City",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 66,
    "type": "group",
    "group": "H",
    "matchday": 3,
    "localDate": "06/27/2026 17:00",
    "date": "2026-06-27T13:30:00.000Z",
    "home": "URU",
    "away": "ESP",
    "homeName": "Uruguay",
    "awayName": "Spain",
    "stadium": "Estadio Akron",
    "city": "Guadalajara (Zapopan)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 67,
    "type": "group",
    "group": "L",
    "matchday": 3,
    "localDate": "06/27/2026 17:00",
    "date": "2026-06-27T13:30:00.000Z",
    "home": "PAN",
    "away": "ENG",
    "homeName": "Panama",
    "awayName": "England",
    "stadium": "Estadio BBVA",
    "city": "Monterrey (Guadalupe)",
    "country": "Mexico",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 68,
    "type": "group",
    "group": "L",
    "matchday": 3,
    "localDate": "06/27/2026 17:00",
    "date": "2026-06-27T13:30:00.000Z",
    "home": "CRO",
    "away": "GHA",
    "homeName": "Croatia",
    "awayName": "Ghana",
    "stadium": "AT&T Stadium",
    "city": "Dallas (Arlington, Texas)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 69,
    "type": "group",
    "group": "J",
    "matchday": 3,
    "localDate": "06/27/2026 20:00",
    "date": "2026-06-27T16:30:00.000Z",
    "home": "ALG",
    "away": "AUT",
    "homeName": "Algeria",
    "awayName": "Austria",
    "stadium": "NRG Stadium",
    "city": "Houston",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 70,
    "type": "group",
    "group": "J",
    "matchday": 3,
    "localDate": "06/27/2026 20:00",
    "date": "2026-06-27T16:30:00.000Z",
    "home": "JOR",
    "away": "ARG",
    "homeName": "Jordan",
    "awayName": "Argentina",
    "stadium": "GEHA Field at Arrowhead Stadium",
    "city": "Kansas City",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 71,
    "type": "group",
    "group": "K",
    "matchday": 3,
    "localDate": "06/27/2026 19:30",
    "date": "2026-06-27T16:00:00.000Z",
    "home": "COL",
    "away": "POR",
    "homeName": "Colombia",
    "awayName": "Portugal",
    "stadium": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 72,
    "type": "group",
    "group": "K",
    "matchday": 3,
    "localDate": "06/27/2026 19:30",
    "date": "2026-06-27T16:00:00.000Z",
    "home": "TBD",
    "away": "UZB",
    "homeName": "IC Path 1 Winner",
    "awayName": "Uzbekistan",
    "stadium": "Hard Rock Stadium",
    "city": "Miami (Miami Gardens)",
    "country": "United States",
    "source": "rezarahiminia/worldcup2026"
  },
  {
    "id": 73,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Sun Jun 28 12:00 UTC-7",
    "date": "",
    "home": "RSA",
    "away": "CAN",
    "homeName": "South Africa",
    "awayName": "Canada",
    "stadium": "Los Angeles (Inglewood)",
    "city": "Los Angeles (Inglewood)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 74,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Mon Jun 29 16:30 UTC-4",
    "date": "",
    "home": "GER",
    "away": "PAR",
    "homeName": "Germany",
    "awayName": "Paraguay",
    "stadium": "Boston (Foxborough)",
    "city": "Boston (Foxborough)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 75,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Mon Jun 29 19:00 UTC-6",
    "date": "",
    "home": "NED",
    "away": "MAR",
    "homeName": "Netherlands",
    "awayName": "Morocco",
    "stadium": "Monterrey (Guadalupe)",
    "city": "Monterrey (Guadalupe)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 76,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Mon Jun 29 12:00 UTC-5",
    "date": "",
    "home": "BRA",
    "away": "JPN",
    "homeName": "Brazil",
    "awayName": "Japan",
    "stadium": "Houston",
    "city": "Houston",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 77,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jun 30 17:00 UTC-4",
    "date": "",
    "home": "FRA",
    "away": "TBD",
    "homeName": "France",
    "awayName": "Sweden",
    "stadium": "New York/New Jersey (East Rutherford)",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 78,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jun 30 12:00 UTC-5",
    "date": "",
    "home": "CIV",
    "away": "NOR",
    "homeName": "Ivory Coast",
    "awayName": "Norway",
    "stadium": "Dallas (Arlington)",
    "city": "Dallas (Arlington)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 79,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jun 30 19:00 UTC-6",
    "date": "",
    "home": "MEX",
    "away": "ECU",
    "homeName": "Mexico",
    "awayName": "Ecuador",
    "stadium": "Mexico City",
    "city": "Mexico City",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 80,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Wed Jul 1 12:00 UTC-4",
    "date": "",
    "home": "ENG",
    "away": "TBD",
    "homeName": "England",
    "awayName": "DR Congo",
    "stadium": "Atlanta",
    "city": "Atlanta",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 81,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Wed Jul 1 17:00 UTC-7",
    "date": "",
    "home": "USA",
    "away": "TBD",
    "homeName": "USA",
    "awayName": "Bosnia & Herzegovina",
    "stadium": "San Francisco Bay Area (Santa Clara)",
    "city": "San Francisco Bay Area (Santa Clara)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 82,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Wed Jul 1 13:00 UTC-7",
    "date": "",
    "home": "BEL",
    "away": "SEN",
    "homeName": "Belgium",
    "awayName": "Senegal",
    "stadium": "Seattle",
    "city": "Seattle",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 83,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Thu Jul 2 19:00 UTC-4",
    "date": "",
    "home": "POR",
    "away": "CRO",
    "homeName": "Portugal",
    "awayName": "Croatia",
    "stadium": "Toronto",
    "city": "Toronto",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 84,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Thu Jul 2 12:00 UTC-7",
    "date": "",
    "home": "ESP",
    "away": "AUT",
    "homeName": "Spain",
    "awayName": "Austria",
    "stadium": "Los Angeles (Inglewood)",
    "city": "Los Angeles (Inglewood)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 85,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Thu Jul 2 20:00 UTC-7",
    "date": "",
    "home": "SUI",
    "away": "ALG",
    "homeName": "Switzerland",
    "awayName": "Algeria",
    "stadium": "Vancouver",
    "city": "Vancouver",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 86,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Fri Jul 3 18:00 UTC-4",
    "date": "",
    "home": "ARG",
    "away": "CPV",
    "homeName": "Argentina",
    "awayName": "Cape Verde",
    "stadium": "Miami (Miami Gardens)",
    "city": "Miami (Miami Gardens)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 87,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Fri Jul 3 20:30 UTC-5",
    "date": "",
    "home": "COL",
    "away": "GHA",
    "homeName": "Colombia",
    "awayName": "Ghana",
    "stadium": "Kansas City",
    "city": "Kansas City",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 88,
    "type": "round-of-32",
    "group": "",
    "matchday": 0,
    "localDate": "Fri Jul 3 13:00 UTC-5",
    "date": "",
    "home": "AUS",
    "away": "EGY",
    "homeName": "Australia",
    "awayName": "Egypt",
    "stadium": "Dallas (Arlington)",
    "city": "Dallas (Arlington)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 89,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Sat Jul 4 17:00 UTC-4",
    "date": "",
    "home": "PAR",
    "away": "FRA",
    "homeName": "Paraguay",
    "awayName": "France",
    "stadium": "Philadelphia",
    "city": "Philadelphia",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 90,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Sat Jul 4 12:00 UTC-5",
    "date": "",
    "home": "CAN",
    "away": "MAR",
    "homeName": "Canada",
    "awayName": "Morocco",
    "stadium": "Houston",
    "city": "Houston",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 91,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Sun Jul 5 16:00 UTC-4",
    "date": "",
    "home": "BRA",
    "away": "NOR",
    "homeName": "Brazil",
    "awayName": "Norway",
    "stadium": "New York/New Jersey (East Rutherford)",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 92,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Sun Jul 5 18:00 UTC-6",
    "date": "",
    "home": "MEX",
    "away": "ENG",
    "homeName": "Mexico",
    "awayName": "England",
    "stadium": "Mexico City",
    "city": "Mexico City",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 93,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Mon Jul 6 14:00 UTC-5",
    "date": "",
    "home": "POR",
    "away": "ESP",
    "homeName": "Portugal",
    "awayName": "Spain",
    "stadium": "Dallas (Arlington)",
    "city": "Dallas (Arlington)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 94,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Mon Jul 6 17:00 UTC-7",
    "date": "",
    "home": "USA",
    "away": "BEL",
    "homeName": "USA",
    "awayName": "Belgium",
    "stadium": "Seattle",
    "city": "Seattle",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 95,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jul 7 12:00 UTC-4",
    "date": "",
    "home": "W86",
    "away": "W88",
    "homeName": "W86",
    "awayName": "W88",
    "stadium": "Atlanta",
    "city": "Atlanta",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 96,
    "type": "round-of-16",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jul 7 13:00 UTC-7",
    "date": "",
    "home": "SUI",
    "away": "W87",
    "homeName": "Switzerland",
    "awayName": "W87",
    "stadium": "Vancouver",
    "city": "Vancouver",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 97,
    "type": "quarter-final",
    "group": "",
    "matchday": 0,
    "localDate": "Thu Jul 9 16:00 UTC-4",
    "date": "",
    "home": "W89",
    "away": "W90",
    "homeName": "W89",
    "awayName": "W90",
    "stadium": "Boston (Foxborough)",
    "city": "Boston (Foxborough)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 98,
    "type": "quarter-final",
    "group": "",
    "matchday": 0,
    "localDate": "Fri Jul 10 12:00 UTC-7",
    "date": "",
    "home": "W93",
    "away": "W94",
    "homeName": "W93",
    "awayName": "W94",
    "stadium": "Los Angeles (Inglewood)",
    "city": "Los Angeles (Inglewood)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 99,
    "type": "quarter-final",
    "group": "",
    "matchday": 0,
    "localDate": "Sat Jul 11 17:00 UTC-4",
    "date": "",
    "home": "W91",
    "away": "W92",
    "homeName": "W91",
    "awayName": "W92",
    "stadium": "Miami (Miami Gardens)",
    "city": "Miami (Miami Gardens)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 100,
    "type": "quarter-final",
    "group": "",
    "matchday": 0,
    "localDate": "Sat Jul 11 20:00 UTC-5",
    "date": "",
    "home": "W95",
    "away": "W96",
    "homeName": "W95",
    "awayName": "W96",
    "stadium": "Kansas City",
    "city": "Kansas City",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 101,
    "type": "semi-final",
    "group": "",
    "matchday": 0,
    "localDate": "Tue Jul 14 14:00 UTC-5",
    "date": "",
    "home": "W97",
    "away": "W98",
    "homeName": "W97",
    "awayName": "W98",
    "stadium": "Dallas (Arlington)",
    "city": "Dallas (Arlington)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 102,
    "type": "semi-final",
    "group": "",
    "matchday": 0,
    "localDate": "Wed Jul 15 15:00 UTC-4",
    "date": "",
    "home": "W99",
    "away": "W100",
    "homeName": "W99",
    "awayName": "W100",
    "stadium": "Atlanta",
    "city": "Atlanta",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 103,
    "type": "match-for-third-place",
    "group": "",
    "matchday": 0,
    "localDate": "Sat Jul 18 17:00 UTC-4",
    "date": "",
    "home": "L101",
    "away": "L102",
    "homeName": "L101",
    "awayName": "L102",
    "stadium": "Miami (Miami Gardens)",
    "city": "Miami (Miami Gardens)",
    "country": "",
    "source": "openfootball/worldcup"
  },
  {
    "id": 104,
    "type": "final",
    "group": "",
    "matchday": 0,
    "localDate": "Sun Jul 19 15:00 UTC-4",
    "date": "",
    "home": "W101",
    "away": "W102",
    "homeName": "W101",
    "awayName": "W102",
    "stadium": "New York/New Jersey (East Rutherford)",
    "city": "New York/New Jersey (East Rutherford)",
    "country": "",
    "source": "openfootball/worldcup"
  }
];

export const tournamentStats = {
  teams: worldCupTeams.length,
  groups: worldCupGroups.length,
  matches: worldCupMatches.length,
  stadiums: worldCupStadiums.length,
  groupMatches: worldCupMatches.filter((match) => match.type === "group").length,
  knockoutMatches: worldCupMatches.filter((match) => match.type !== "group").length,
};
